# Generated by Django 4.2 on 2023-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=40, verbose_name='product name')),
                ('prodescription', models.TextField(verbose_name='product Description')),
                ('procost', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='product Cost')),
                ('proprice', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='product Price')),
                ('procreated', models.DateTimeField(verbose_name='product day and time of creation')),
            ],
        ),
    ]
