# Generated by Django 4.2 on 2023-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='proIimage',
            field=models.ImageField(upload_to='product/images', verbose_name='product Image'),
        ),
    ]
