# Generated by Django 4.1.7 on 2023-04-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='ParentCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
