# Generated by Django 4.2 on 2023-04-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productcategory_parentcategory_productalt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCPLAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ACC', to='product.product', verbose_name='product Accessory')),
                ('AcCCAlternative', models.ManyToManyField(related_name='alternative_ACC', to='product.product', verbose_name='Alternative Accessory')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
