# Generated by Django 4.2 on 2023-04-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0009_productaccessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='product Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='proCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory', verbose_name='productCategory'),
        ),
    ]
