# Generated by Django 4.2 on 2023-04-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0010_product_probrand_product_procategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proVariant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.variant', verbose_name='product variant'),
        ),
    ]
