# Generated by Django 4.2 on 2023-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_provariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proIimage',
            field=models.ImageField(blank=True, upload_to='product/images', verbose_name='product Image'),
        ),
    ]
