# Generated by Django 4.2 on 2023-05-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_proslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodiscount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='product discount'),
            preserve_default=False,
        ),
    ]
