# Generated by Django 4.2 on 2023-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_prodiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proisbest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='proisnew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodiscount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='product discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proprice',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='product Price'),
        ),
    ]
