# Generated by Django 4.1.7 on 2023-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_proisbest_product_proisnew_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='proisbest',
            field=models.BooleanField(default=False, verbose_name='product is best!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proisnew',
            field=models.BooleanField(default=True, verbose_name='product is new!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proslug',
            field=models.SlugField(blank=True, null=True, verbose_name='product slug'),
        ),
    ]
