# Generated by Django 4.1.7 on 2023-05-12 23:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('prfile_image', models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='profile image')),
                ('address', models.CharField(max_length=100)),
                ('joinDate', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 1, 46, 58, 580909), verbose_name='joinDate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
